### ISSUE TITLE
some of the spring boot quickstarts don't get their kubernetes.json files generated properly

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/quickstarts#256]
e.g. the camel and activemq quickstarts

**Comment by jstrachan** [comment]
looks like others don't have an image zip either - e.g. webmvc
http://central.maven.org/maven2/io/fabric8/jube/images/fabric8/springboot-webmvc/2.0.32/

**Comment by davsclaus** [comment]
Yep still a problem with these 2, all the others have a kubernetes.json generated.

**Comment by davsclaus** [comment]
Yes the jube images is not generated for spring-boot quickstarts, see #290
