### ISSUE TITLE
the war quickstarts should also define a service so folks can invoke the web app from the services tab in hawtio

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/quickstarts#28]

**Comment by davsclaus** [comment]
i believe this is possible now.

**Comment by davsclaus** [comment]
They are all nicely there

![screen shot 2015-06-16 at 2 22 46 pm](https://cloud.githubusercontent.com/assets/477100/8182719/74db3f84-1432-11e5-9a4e-e672465deacd.png)
