### ISSUE TITLE
Generate kubernetes.json has a very long description

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#413]
Seems like it slurps the entire readme.md content. I think it should grab the the first section, eg until a new header is detected,

"fabric8/description" : "# Web MVC with Spring-Boot QuickStart\n\nThis example assumes that you have a running openshift v3, and fabric8 v2 using docker.\nFor more info see http://fabric8.io/v2/getStarted.html.\n\nThis example demonstrates how you can use Spring Boot and web mvc with a [Java Container](http://fabric8.io/gitbook/javaContainer.html)\n\nThe quickstart uses Spring Boot to configure a little Spring MVC application that offers a REST service.\n\nWhen the application is running, you can use a web browser to access the REST service, as the screenshot below shows:\n\n![Spring Boot MVC](https://raw.githubusercontent.com/fabric8io/fabric8/1.x/docs/images/spring-boot-mvc.png)\n\n\n### Building this example\n\nThe example comes as source code and pre-built binaries with the fabric8 distribution. \n\nTo try the example you do not need to build from source first. Although building from source allows you to modify the source code, and re-deploy the changes to fabric. See more details on the fabric8 website about the [developer workflow](http://fabric8.io/gitbook/developer.html).\n\nTo build and run from the source code:\n\n1. Change your working directory to `quickstarts/spring-boot/webmvc` directory.\n1. Run `./build-and-run.sh` to build and run the quickstart.\n\n\n### Using the web console\n\nYou can deploy and run this example from the web console, as follows\n\n1. It is assumed that you have already created a fabric and are logged into a container called `root`.\n1. Login the web console\n1. Click the Wiki button in the navigation bar\n1. Select `quickstarts` --> `spring-boot` --> `webmvc`\n1. Click the `New` button in the top right corner\n1. In the Create New Container page, enter `mychild` in the Container Name field, and click the *Create and start container* button\n\n## How to try this example\n\n1. Using the hawtio console at http://dockerhost:8484/hawtio, you should now see simple java as a 'pod' under the kubernetes tab http://dockerhost:8484/hawtio/kubernetes/pods?_id=\n1. You can find out the containerId using `docker ps` - the output should look something like:\n```\n\tCONTAINER ID        IMAGE                                                   COMMAND                CREATED             STATUS              PORTS                    NAMES\n\t19d5280bf22e        dockerhost:5000/quickstart/quickstart/springboot-webmvc:2.2-SNAPSHOT   /bin/sh -c 'java $JA   3 days ago          Up 28 minutes                                k8s_quickstart-java-simple-fatjar.6c2fc62f_c6fa4631-588f-11e4-8746-406c8f215ad7.etcd_c6fa4631-588f-11e4-8746-406c8f215ad7_e28ca78b\n```\n1. Use `docker logs -f <CONTAINER ID>` to see what the Spring Boot app is writing to the console, and\nsee that every second it logs another line:\n```\n\tHello Fabric8! Here's your random string: NMsq3\n\tHello Fabric8! Here's your random string: wPzMW\n\tHello Fabric8! Here's your random string: tiTpX\n```\n1. At this point you have verified that things work but additionally we can find out some more about this container.\nFirst `docker inspect <image>` to see all the metadata. For instance part of this output reads\n```\n....\n     \"Env\": [\n            \"HOME=/\",\n            \"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\n            \"JOLOKIA_VERSION=1.2.2\",\n            \"CLASSPATH=/maven/*:/maven\",\n            \"JAVA_OPTIONS=-javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0,port=8778,agentId=$HOSTNAME\",\n            \"MAIN=io.fabric8.quickstarts.java.simple.Main\"\n        ],\n        \"Cmd\": [\n            \"/bin/sh\",\n            \"-c\",\n            \"java $JAVA_OPTIONS -cp $CLASSPATH $MAIN $ARGUMENTS\"\n        ],\n....\n```\nwhich shows our java process is started using a Cmd, and that it is uing the io.fabric8.quickstarts.java.simple.Main class to start it, with a classpath of everything in the /maven directory. The JAVA_OPTION start a jolokia agent.\n\n1. Using `docker top d356604acb80` we can see simple java process as well as the jolokia agent.\n```\n\tPID                 USER                COMMAND\n\t2624                root                /bin/sh -c java $JAVA_OPTIONS -cp $CLASSPATH $MAIN $ARGUMENTS\n\t2643                root                java -javaagent:/opt/jolokia/jolokia.jar=host=0.0.0.0,port=8778,agentId=$HOSTNAME -cp /maven/*:/maven io.fabric8.quickstarts.java.simple.Main\n```\n1. You use NSEnter (https://github.com/jpetazzo/nsenter) to connect to the container using the alias `docker-enter <containerId>`. We can inspect the file system and see our jars in the /maven directory \n```\n\t/maven# ls -l\n\ttotal 412\n\t-rw-r--r-- 1 root root 412739 Oct 20  2014 commons-lang3-3.3.2.jar\n\t-rw-r--r-- 1 root root   4453 Oct 20  2014 java-simple-fatjar-2.0.0-SNAPSHOT.jar\n```\nand the jolokia jars in the /opt/jolokia directory\n```\n\topt/jolokia# ls -l\n\ttotal 388\n\t-rw-r--r-- 1 root root 389459 Jun 14 17:43 jolokia.jar\n\t-rw-r--r-- 1 root root    871 Oct  8 09:33 jolokia_env.sh\n```\n\n## Undeploy this example\n\nThe following information is divided into two sections, whether you are using the command line shell in fabric, or using the web console\n\n### Using the OpenShift Kube command line shell\n\nTo stop and undeploy the example using the OpenShift Kube command line, enter the following commands at the console:\n\n        openshift kube stop quickStartJavaSimpleController\n        openshift kube rm quickStartJavaSimpleController\n\n### Using the web console\n\nTo stop and undeploy the example in fabric8:\n\n1. In the web console, click the *Runtime* button in the navigation bar.\n1. Select the `mychild` container in the *Containers* list, and click the *Stop* button in the top right corner\n",
      "fabric8/iconUrl" :

**Comment by davsclaus** [comment]
The readme is from
https://github.com/fabric8io/quickstarts/tree/master/quickstarts/spring-boot/webmvc

**Comment by davsclaus** [comment]
Its a bit better now that we have trimmed the readme of the quickstarts to be shorter.

**Comment by davsclaus** [comment]
I can see in the code that we also slurp the summary.md, so maybe  for short hand descriptions we should use summary.md, and then include the entire documentation as description, as it does today.

**Comment by jstrachan** [comment]
yeah - for completeness we're kinda replicating the AppZip stuff; (readme + summary + icon) inside the OpenShift Template as annotations; so that we've a place to put the summary / readme / icon that the console can use).
