### ISSUE TITLE
The karaf docker quickstarts do not startup - they output about jboss sti

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#454]
If you build the quickstarts and

```
cd quickstarts/karaf/camel-log
mvn clean install docker:build
```

And then run the docker image
```
davsclaus:~/workspace/quickstarts/quickstarts/karaf/camel-log (master)/$ docker run -it -p 8181:8181 -p 8778:8778 fabric8/quickstart-karaf-camellog:2.2-SNAPSHOT
This is an STI ready Apache Karaf image.
You can use it with the sti tool, to build a docker image out of your source code.

sti build <url to git repo> fabric8/karaf-<version> <target image name>

The git url is expected to host a maven project for karaf, that will generate as part of its output any of the following:

i) One or more kar archives.
ii) A maven repo under fabric8/repository


Running an empty container:
to spin up an empty karaf container with this image you can just:

docker run fabric8/karaf-<version> deploy-and-start

Details:
If a pom.xml is present in the source directory, the project is built with maven and the
output in target will be copied into the /opt/jboss/deploy directory.
davsclaus:~/workspace/quickstarts/quickstarts/karaf/camel-log (master)/$
```

If you manually start the image with /bin/bash

```
davsclaus:~/workspace/quickstarts/quickstarts/karaf/camel-log (master)/$ docker run -it -p 8181:8181 -p 8778:8778 fabric8/quickstart-karaf-camellog:2.2-SNAPSHOT /bin/bash
```

Then you can deploy the quickstart with
```
cp deploy/quickstart-karaf-camellog.kar karaf/deploy/
```

And start karaf
```
[jboss@6a2370e20cca ~]$ cd karaf/
[jboss@6a2370e20cca karaf]$ bin/karaf
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://172.17.0.41:8778/jolokia/
        __ __                  ____
       / //_/____ __________ _/ __/
      / ,<  / __ `/ ___/ __ `/ /_
     / /| |/ /_/ / /  / /_/ / __/
    /_/ |_|\__,_/_/   \__,_/_/

  Apache Karaf (2.4.2)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'osgi:shutdown' or 'logout' to shutdown Karaf.
```

And it runs if you do a log:tail
```
log:tail
2015-06-05 17:07:52,711 | INFO  | #0 - timer://foo | log-route                        | ?                                   ? | 58 - org.apache.camel.camel-core - 2.15.2 | >>> Hello from Fabric based Camel route! :
...
```

**Comment by davsclaus** [comment]
So we are not so far from having it to work.

Seems like some deploy script needs to run to copy the *.kar to the karaf/deploy dir. And then start karaf itself with bin/karaf.

**Comment by davsclaus** [comment]
And jolokia works also

![screen shot 2015-06-05 at 7 14 18 pm](https://cloud.githubusercontent.com/assets/477100/8011136/6315ae94-0bb6-11e5-8733-049bcf8db17d.png)

**Comment by davsclaus** [comment]
@rhuss @iocanel - the karaf docker images is not there yet, but we are getting closer.

**Comment by davsclaus** [comment]
ps this is done with just pure boot2docker and not using kubernetes / os3 etc.

**Comment by rhuss** [comment]
Setting the command to `deploy-and-start` should do the trick.

**Comment by rhuss** [comment]
Maybe we can change the scripts that the usage message only is shown if there is nothing to deploy ? And otherwise, simply fire up karaf (so user of the base image do not need to worry about how to start it if there is sth to deploy available)

Opinions ?

**Comment by jimmidyson** [comment]
Can't we just put the kars directly in the karaf deploy dir at image build time? Moving or coping around artifacts in the container filesystem as will use extra disk space for each instance of the container.

**Comment by rhuss** [comment]
This is already the case. The point is, that the CMD of the base image is `/usr/bin/usage` instead of `/usr/bin/start-and-deploy`. The files are already in place, the startup script only does a symbolic link for each deployment unit.

**Comment by rhuss** [comment]
I would include the usage message int `start-and-deploy` (which btw would better be called `deploy-and-start`, nitpicking I know :) and show it if there is nothing to deploy, nothing to compile.
