### ISSUE TITLE
Make logging in our base images and karaf etc log to stdout,stderr

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#488]
as otherwise we cannot see the logs from osc logs, or from the centralized logging stuff
```
^Cdavsclaus:~/workspace/camel/components/camel-websocket (master)/$ osc logs quickstart-karaf-camel-amq-es8j5 -f
Copying offline repo
Checking for kars in /opt/jboss/deploy/kars
Linking /opt/jboss/deploy/quickstart-karaf-camel-amq.kar --> /opt/jboss/karaf/deploy/quickstart-karaf-camel-amq.kar
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://172.17.0.65:8778/jolokia/
```

This is all we see from the karaf quickstart, the karaf container does some logging but that is to data/logs/karaf.log.

We should configure it to log to stdout also

**Comment by davsclaus** [comment]
wonder if @rhuss this requires any changes to our base images? And if so something you can help with?

**Comment by davsclaus** [comment]
eg we should make sure the java / tomcat / karaf / images logs so we can capture the logging from osc / kubernetes

**Comment by rhuss** [comment]
I can check and implement that all logs from the appserver of fabric8/docker-appserver are configured to log to standard out.

**Comment by rhuss** [comment]
For Karaf I implemented this in the Dockerfile. Please note also fabric8io/docker-appserver#1 since currently I'm maintaining multiple forks of this repo which doesn't make much sense in the long run. I think we need quite some consolidation on all the fabric8 Docker base images floating around. I will collect a list and make a suggestion then (but somewhere else than in this issue ;-)

I will check Jetty and Tomcat now, too.

**Comment by rhuss** [comment]
Jetty logging to stdout works now, too.

**Comment by davsclaus** [comment]
Thanks what about the plain fabric8-java image ?

**Comment by davsclaus** [comment]
tomcat is still pending, I tried today and I only see the tomcat logs, and not from my app which was configured to log to the console

**Comment by davsclaus** [comment]
@rhuss do you have time to do the same magic on tomcat containers - as would be nice to have that working for the barcalona trip

**Comment by rhuss** [comment]
ok, will do it ASAP

**Comment by rhuss** [comment]
@davsclaus do you see the logs from you app in some other log files, e.g. `/opt/tomcat/logs/localhost.2015-06-22.log` ? Maybe you app uses some custom logging ?

For me, logging to standard out (`System.out.println()`) already ends up in the Tomcat console (fabric8/tomcat-8.0 image).

**Comment by davsclaus** [comment]
Ah its a war app that has a configured log4.properties that uses slf4j-log4j to log. its configured for console, eg
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/war/camel-servlet/src/main/resources/log4j.properties

eg all those Java libraries uses commons-logging or slf4j-api for logging, and not system.out. So we should find a way to make all that logging just work .. if possible

**Comment by davsclaus** [comment]
eg if I do a 

oc logs xxxx

where xxx is the pod id of the tomcat image such as the camel-servlet etc or any other, then I only see the tomcat logs, and not the app itself. Though you need to tweak the quickstart to do some logging on a per request. But Camel itself logs when it start / stop etc so we should see that too, but i only see the general tomcat logging

**Comment by davsclaus** [comment]
I am adding so the WAR quickstarts does logging per request so its easier for us to try and test

**Comment by rhuss** [comment]
I will try it here locally. Really wonder where the ConsoleAppender ends up if not on standard out :) I tried the integration jolokia-it.war which writes to standard out directly, that works as expected.

**Comment by davsclaus** [comment]
Okay the rest quickstart which is only CXF logs now per request
```
22-Jun-2015 14:08:59.597 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
22-Jun-2015 14:08:59.621 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
22-Jun-2015 14:08:59.625 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 6496 ms
2015-06-22 14:09:02,875 [nio-8080-exec-1] INFO  CustomerService                - Invoking getCustomer, Customer id is: 123
2015-06-22 14:09:07,534 [nio-8080-exec-2] INFO  CustomerService                - Invoking getCustomer, Customer id is: 123
2015-06-22 14:09:12,537 [nio-8080-exec-3] INFO  CustomerService                - Invoking getCustomer, Customer id is: 123
```

it has no Camel so that seems okay. I configured it to use log4j which it did not do before.

**Comment by rhuss** [comment]
So, does it work now with logging to stdout ?

**Comment by davsclaus** [comment]
Ah seems like the camel-servlet didnt include log4j jar so that is why it wont log to console. It works now yay!!!

**Comment by rhuss** [comment]
When I start up the camel quickstart war I get this

````
22-Jun-2015 14:09:14.197 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.23
22-Jun-2015 14:09:14.234 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /opt/apache-tomcat-8.0.23/webapps/camel.war
22-Jun-2015 14:09:25.288 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2015-06-22 14:09:26,050 [ost-startStop-1] INFO  ContextLoader                  - Root WebApplicationContext: initialization started
2015-06-22 14:09:27,016 [ost-startStop-1] INFO  XmlWebApplicationContext       - Refreshing Root WebApplicationContext: startup date [Mon Jun 22 14:09:27 UTC 2015]; root of context hierarchy
2015-06-22 14:09:27,402 [ost-startStop-1] INFO  XmlBeanDefinitionReader        - Loading XML bean definitions from class path resource [camel-config.xml]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
````

which meens there is some issue with the deps in the war (the sl4j static bridge is missing). I will check this.

**Comment by rhuss** [comment]
ok, you alread found it, so I leave it to you ;)

**Comment by davsclaus** [comment]
yep all the rest now logs and `oc logs` can see the logging in real time. And it works for the java images also.

**Comment by davsclaus** [comment]
yay it works now. I think we should be good now.
