### ISSUE TITLE
amqbroker app - Should have better labels

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#489]
Wonder if the provider can be = fabric8
And the group could be something that unites the brokers such as = broker    or activemq    or amq

We also have another mq app called mqbroker. So we have 2 apps for "the same".

See screenshot
![screen shot 2015-06-16 at 3 00 26 pm](https://cloud.githubusercontent.com/assets/477100/8183376/efab326e-1437-11e5-8efe-4bb65d0f6183.png)

**Comment by davsclaus** [comment]
@rajdavies  we have 2 apps for ActiveMQ broker - is this on purpose?

https://github.com/fabric8io/quickstarts/tree/master/apps/amqbroker

https://github.com/fabric8io/quickstarts/tree/master/apps/fabric8mq

**Comment by davsclaus** [comment]
btw the fabric8mq has these labels

![screen shot 2015-06-16 at 3 10 56 pm](https://cloud.githubusercontent.com/assets/477100/8183550/26673720-1439-11e5-83ff-dfad58c46db0.png)

**Comment by rajdavies** [comment]
Fixed
