### ISSUE TITLE
apiman app - uses old versions of weld / jetty etc

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#503]
@KurtStam do you have any thoughts on apiman app uses old versions
https://github.com/fabric8io/quickstarts/blob/master/apps/apiman/pom.xml#L27

jetty 8 is EOL and jboss weld is on 2.x as stable etc.

If possible we should try to align this to use same versions as we have defined in the root pom.xml in the fabric8 project.
https://github.com/fabric8io/fabric8/blob/master/pom.xml

**Comment by KurtStam** [comment]
@davsclaus, it should be no problem to upgrade. You can assign to me.
