### ISSUE TITLE
Remove jolokia-access.xml

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#509]
@jimmidyson tested today that the CORS should be fixed in latest releases, so we can remove this workaround for our quickstarts.

**Comment by jimmidyson** [comment]
Yeah this works fine now with the new proxy endpoint in kube.

**Comment by davsclaus** [comment]
Yay works for me also. I removed them from the quickstarts

**Comment by rhuss** [comment]
Doesn't work anymore :-( Still
