### ISSUE TITLE
Unable to push image [fabric8/quickstart-war-camel-servlet:2.3-SNAPSHOT] to registry [172.30.13.165:5000]

### ISSUE THREAD

**Issue by srecon** [fabric8io/quickstarts#567]
When executing the following command 
mvn docker:push -Ddocker.registry=172.30.13.165:5000 -Ddocker.username=admin -Ddocker.password=admin
to push image though maven plugin, getting the following error:
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.12.0:push (default-cli) on project quickstart-war-camel-servlet: Unable to push image [fabric8/quickstart-war-camel-servlet:2.3-SNAPSHOT] to registry [172.30.13.165:5000] : v1 ping attempt failed with error: Get http://172.30.13.165:5000/v1/_ping: dial tcp 172.30.13.165:5000: i/o timeout (Internal Server Error: 500)

**Comment by davsclaus** [comment]
I think the docker registry is now v2 based, and therefore the v1/_ping do not work. 

Are you using latest fabric8 release eg 2.2.5 ?

**Comment by srecon** [comment]
I am using 2.2.3 version of fabric8 by vagrant. Thanks for the hints, i will make a try on 2.2.5 version.
